name: Greeting from Liu Yunzhi
on: push
  
jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: LIU
        MIDDLE_NAME: George
        LAST_NAME: Yunzhi
  run: |
    echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
